changelog:
  exclude:
    labels:
      - "ignore-for-release"
  categories:
    - title: 🧪 MASTG Test Cases
      labels:
        - "tests"
    - title: 📖 MASTG Testing Fundamentals
      labels:
        - "fundamentals"
    - title: ✨ MASTG Testing Techniques
      labels:
        - "techniques"
    - title: 🪄 MASTG Testing Tools
      labels:
        - "tools"
    - title: 🐞 Errata Corrections
      labels:
        - "errata"
    - title: ⚡ Automation
      labels:
        - "automation"
    - title: 📜 Mobile Security Checklists
      labels:
        - "checklists"
    - title: 🎉 New Donators
      labels:
        - "donation"
    - title: Other Changes
      labels:
        - "*"
   
