name: Make a Donation
description: Donate to the OWASP Mobile Security Project.
title: "[Donation]: "
labels: ["org", "donation"]
assignees:
  - cpholguera
body:
  - type: input
    id: name
    attributes:
      label: Your Name
    validations:
      required: true

  - type: input
    id: company
    attributes:
      label: Company Name
      description: What's the name of your company?
      placeholder: ex. Nice Security Ltd.
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: E-Mail Address
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true

  - type: input
    id: amount
    attributes:
      label: Donation Amount
      description: How much would you like to donate?
      placeholder: ex. USD 2000
    validations:
      required: false

  - type: dropdown
    id: MSTG Paperback Copies
    attributes:
      label: Version
      description: Would you like to receive the paperback copie(s) of the MSTG as indicated in your Donation Package?
      options:
        - No, please save the money for the project and contribute to the envorinment.
        - Yes, please send them to me.
    validations:
      required: true
