name: Make a Donation
description: Donate to the OWASP Mobile Security Project.
title: "[Donation]: "
labels: ["org", "donation"]
assignees:
  - cpholguera
body:
  - type: input
    id: name
    attributes:
      label: Your Name
    validations:
      required: true

  - type: input
    id: company
    attributes:
      label: Company Name
      description: What's the name of your company?
      placeholder: ex. Nice Security Ltd.
    validations:
      required: true
      
