name: Make a Donation
description: Donate to the OWASP Mobile Security Project.
title: "[Donation]: "
labels: ["org", "donation"]
assignees:
  - cpholguera
body:
  - type: input
    id: name
    attributes:
      label: Your Name
    validations:
      required: true

  - type: input
    id: company
    attributes:
      label: Company Name
      description: What's the name of your company?
      placeholder: ex. Nice Security Ltd.
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: E-Mail Address
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true

  - type: input
    id: amount
    attributes:
      label: Donation Amount
      description: How much would you like to donate?
      placeholder: ex. USD 2000
    validations:
      required: false
