name: Spell Check

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spell-check:
    name: Spell Check (Full)
    uses: ./.github/workflows/reusable-spell-checker.yml
    secrets: inherit
