name: Main Branch Checks

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - cluster-workflows

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spell-check:
    name: Spell Check (Full)
    uses: ./.github/workflows/reusable-spell-checker.yml
    secrets: inherit

  url-check:
    name: URL Check (Full)
    uses: ./.github/workflows/reusable-url-checker.yml
    secrets: inherit

  markdown-lint:
    name: Markdown Lint
    uses: ./.github/workflows/reusable-markdown-linter.yml
    secrets: inherit
