name: Markdown Lint

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - cluster-workflows

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdown-lint:
    name: Markdown Lint
    uses: ./.github/workflows/reusable-markdown-linter.yml
    secrets: inherit
